### ISSUE TITLE
ReadMe Updates

### ISSUE THREAD

**Issue by SharedMocha** [elastos/Elastos.ELA.Pay#1]
# Elastos.ELA.Pay(English&Chinese)
Hello everyone, 
Welcome to ELA PAY!

Below is a brief description of  Elapay.

Elapay is a payment tool (or) app that lets you pay with ELA.Two types of payments are supported:
1.)Pay on order(Example-Paying at a store)
2.)Point to point pay and receipt.(Example-Paying to a friend)

The first type requires merchants to integrate  Elapay service into their web apps so that users can choose this service along with other options like "PayPal, Credit card payments or third party payment".

The second type is like  a h5 page that can be shared in social media like facebook,wechat to pay someone or accept ELA.

A commodity, product or service can be priced with ELA directly based on the exchange rate (or) can be paid with  legal currency

Elapay can be used in many situations, like in a game or you can buy equipment and transact with ELA, you can also use  ELA on a shopping website.

Elapay是一种用ELA币进行交易和支付的工具，Elapay主要有两种类型：订购类支付和点对点收付款。
订购类支付，即商家在自己的WEB和APP服务里集成Elapay支付功能，使其成为与其它支付方式，比如银行卡、第三方支付工具等并列可选的支付选项；第二种则是支持点对点进行ELA币收、付款操作的操作，通过发起一个收、付款h5页面，在facebook、wechat等各类社交场景下进行分享，连接ELA钱包后进行支付操作。
对于商品和服务的标价，Elapay提供两种方式，直接用ELA标价，或者用法币基于动态汇率计算ELA标价。
基于这样的设计，Elapay可以用于很多场景，比如在游戏里，所有的装备都使用ELA标价与购买，个人玩家也可以互相点对点交易；在购物，用户可以点对点用ELA直接支付.

**Comment by songsjun** [comment]
Very thank you

**Comment by songsjun** [comment]
I have updated. Thank you.
Next time, you can directly edit it. Welcome together.
